version: 2.1

jobs:
    build:
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - run:
                name: Dependencies
                command: |
                    sudo ./install.bash
            - run:
                name: Build
                command: |
                    ./build.bash
            - run:
                name: Test
                command: |
                    echo "Test"
