version: 2.1

jobs:
    build:
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - run:
                name: Dependencies
                command: |
                    sudo ./scripts/install.bash
            - run:
                name: Build
                command: |
                    make build
            - run:
                name: Install
                command: |
                    make install
            - run:
                name: Test
                command: |
                    echo "Test"
